# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Note(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, name: str=None, note: str=None):  # noqa: E501
        """Note - a model defined in Swagger

        :param id: The id of this Note.  # noqa: E501
        :type id: int
        :param name: The name of this Note.  # noqa: E501
        :type name: str
        :param note: The note of this Note.  # noqa: E501
        :type note: str
        """
        self.swagger_types = {
            'id': int,
            'name': str,
            'note': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'note': 'note'
        }
        self._id = id
        self._name = name
        self._note = note

    @classmethod
    def from_dict(cls, dikt) -> 'Note':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Note of this Note.  # noqa: E501
        :rtype: Note
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Note.


        :return: The id of this Note.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Note.


        :param id: The id of this Note.
        :type id: int
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this Note.


        :return: The name of this Note.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Note.


        :param name: The name of this Note.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def note(self) -> str:
        """Gets the note of this Note.


        :return: The note of this Note.
        :rtype: str
        """
        return self._note

    @note.setter
    def note(self, note: str):
        """Sets the note of this Note.


        :param note: The note of this Note.
        :type note: str
        """
        if note is None:
            raise ValueError("Invalid value for `note`, must not be `None`")  # noqa: E501

        self._note = note
